project_name_override: datacore-client   # distribution (PyPI/project)
package_name_override: datacore_client  # importable package
class_name: DatacoreClient
use_path_prefixes_for_title_model_names: true
package_version_override: 0.1.0
